[package]
name = "rv-gem-types"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = "7.2.0"
either = "1.13.0"
thiserror = "1.0.65"
regex = "1.11.1"
once_cell = "1.20.1"

[dev-dependencies]
insta = "1.34.0"
