[package]
name = "rv-ruby"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_fs = "1.1.3"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_with = "3.14.0"
thiserror = "2.0.12"
tracing = "0.1.41"
