[package]
name = "rv-dirs"
version = "0.1.0"
edition = "2024"

[dependencies]
camino = "1.1.10"
etcetera = "0.10.0"
tracing = "0.1.41"

[dev-dependencies]
assert_fs = "1.1.3"
fs-err = "3.1.1"
indoc = "2.0.6"
