[package]
name = "rv-dirs"
version = "0.1.0"
edition = "2024"

[dependencies]
etcetera = "0.10.0"
tracing = "0.1.41"
vfs = "0.12.2"

[dev-dependencies]
assert_fs = "1.1.3"
fs-err = "3.1.1"
indoc = "2.0.6"
